### ISSUE TITLE
Loading module with SystemJS

### ISSUE THREAD

**Issue by neilpimley** [AndyMeps/ng2-color-picker#1] opened 2016-12-01 11:51 UTC
Is it possible to the load the module with SystemJS? If so how should it be configured? I have it configured as below
` paths: {`
       `      'npm:': 'node_modules/'`
`  },`
      `   map: {`
       `     ..... ,`
      `     'ng2-bootstrap': 'npm:ng2-bootstrap/bundles/ng2-bootstrap.umd.js',`
      `    'ng2-color-picker': 'npm:ng2-color-picker'`
`  },`
`  packages: {`
`    ....., ,`
`   'ng2-color-picker': { main: 'index.js', defaultExtension: 'js' }`
`}`

It's looking for a file that doesn't exist
Error: Uncaught (in promise): Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-color-picker/src/components.js
Instead of  http://localhost:3000/node_modules/ng2-color-picker/src/components/index.js

**Comment by AndyMeps** [comment] 2016-12-01 16:34
Hi neilpimley,

I'm not too familiar with SystemJS, however it looks like the index path is incorrect, try this:

```javascript
{
'ng2-color-picker': { main: 'lib/index.js', defaultExtension: 'js' }
}
```

Hope this helps, let me know either way!

Regards,

Andy

**Comment by drihm** [comment] 2016-12-07 14:44
Hi @neilpimley,

I had the same issue. This worked for me:

```
var map = {
    …
    'ng2-color-picker': 'app/third-party/ng2-color-picker'
};

var packages = {
    …
    'ng2-color-picker': { main: 'lib/index.js', defaultExtension: 'js', map: {
            './lib/src/components': './lib/src/components/index.js',
            './lib/src/models': './lib/src/models/index.js'
     }}
};
```

Regards

**Comment by AndyMeps** [comment] 2016-12-08 15:17
Closing as a solution has been confirmed, thanks drihm.

**Closed by AndyMeps** 2016-12-08 15:17 UTC
Labels: question
